from __future__ import annotations

from typing import Dict, Optional

from .pricing import ModelPricing, get_model_pricing
from .tokenizer import estimate_tokens


def estimate_task_cost(
    model_name: str,
    prompt_tokens: int,
    completion_tokens: int = 0,
    pricing_override: Optional[Dict[str, float]] = None,
) -> Dict[str, float]:
    """Estimate the cost of a single LLM task based on token usage.

    Args:
        model_name: Canonical model key, e.g. "openai/gpt-4.1".
        prompt_tokens: Number of input tokens consumed by the prompt.
        completion_tokens: Number of output tokens generated by the model.
        pricing_override: Optional overrides for input/output cost per 1k tokens.

    Returns:
        A breakdown of estimated cost values.
    """
    if prompt_tokens < 0 or completion_tokens < 0:
        raise ValueError("Token counts must be non-negative integers.")

    pricing = get_model_pricing(model_name, override=pricing_override)

    input_cost = prompt_tokens * pricing.input_cost_per_1k / 1000.0
    output_cost = completion_tokens * pricing.output_cost_per_1k / 1000.0
    total_cost = input_cost + output_cost

    return {
        "model_name": f"{pricing.provider}/{pricing.model_name}",
        "prompt_tokens": prompt_tokens,
        "completion_tokens": completion_tokens,
        "input_cost": round(input_cost, 8),
        "output_cost": round(output_cost, 8),
        "total_cost": round(total_cost, 8),
        "input_cost_per_1k": pricing.input_cost_per_1k,
        "output_cost_per_1k": pricing.output_cost_per_1k,
    }


def estimate_task_cost_from_text(
    model_name: str,
    prompt_text: str,
    completion_text: str = "",
    pricing_override: Optional[Dict[str, float]] = None,
) -> Dict[str, float]:
    """Estimate the cost of a task using raw prompt and completion text.

    This helper computes token estimates automatically and then delegates to
    `estimate_task_cost()`.
    """
    prompt_tokens = estimate_tokens(prompt_text, model_name=model_name)
    completion_tokens = estimate_tokens(completion_text, model_name=model_name)
    return estimate_task_cost(
        model_name=model_name,
        prompt_tokens=prompt_tokens,
        completion_tokens=completion_tokens,
        pricing_override=pricing_override,
    )


def convert_cost_to_unit(cost_dict: Dict[str, float], unit: str = "1M") -> Dict[str, object]:
    """Convert cost output to a different unit basis.

    Args:
        cost_dict: Cost dictionary from estimate_task_cost().
        unit: Target unit ('1k', '1M', or 'token').

    Returns:
        Cost dictionary with converted per-unit pricing.
    """
    if unit.strip().lower() in {"1k", "k", "1000"}:
        return cost_dict
    if unit.strip().lower() in {"1m", "m", "1000000", "million"}:
        return {
            "model_name": cost_dict["model_name"],
            "prompt_tokens": cost_dict["prompt_tokens"],
            "completion_tokens": cost_dict["completion_tokens"],
            "input_cost": round(cost_dict["input_cost"] * 1000, 8),
            "output_cost": round(cost_dict["output_cost"] * 1000, 8),
            "total_cost": cost_dict["total_cost"],
            "input_cost_per_unit": round(cost_dict["input_cost_per_1k"] * 1000, 8),
            "output_cost_per_unit": round(cost_dict["output_cost_per_1k"] * 1000, 8),
            "unit": "1M",
        }
    if unit.strip().lower() in {"1", "token", "per token"}:
        return {
            "model_name": cost_dict["model_name"],
            "prompt_tokens": cost_dict["prompt_tokens"],
            "completion_tokens": cost_dict["completion_tokens"],
            "input_cost": round(cost_dict["input_cost"], 8),
            "output_cost": round(cost_dict["output_cost"], 8),
            "total_cost": cost_dict["total_cost"],
            "input_cost_per_unit": round(cost_dict["input_cost_per_1k"] / 1000, 10),
            "output_cost_per_unit": round(cost_dict["output_cost_per_1k"] / 1000, 10),
            "unit": "token",
        }
    raise ValueError(f"Unsupported unit '{unit}'. Use '1k', '1M', or 'token'.")
